export const WORDS = [
    {l1: "tunnag", l2: "duck", level: "Intro"},
{l1: "snog", l2: "nice", level: "Intro"},
{l1: "seo", l2: "This is", level: "Intro"},
{l1: "piseag", l2: "kitten", level: "Intro"},
{l1: "muc", l2: "pig", level: "Intro"},
{l1: "Mòrag", l2: "Morag", level: "Intro"},
{l1: "mòr", l2: "big", level: "Intro"},
{l1: "math", l2: "good", level: "Intro"},
{l1: "Irn bru", l2: "Irn Bru", level: "Intro"},
{l1: "Iain", l2: "John", level: "Intro"},
{l1: "gàidhlig", l2: "Gaelic", level: "Intro"},
{l1: "Eilidh", l2: "Helen", level: "Intro"},
{l1: "dona", l2: "bad", level: "Intro"},
{l1: "cù", l2: "dog", level: "Intro"},
{l1: "cearc", l2: "chicken", level: "Intro"},
{l1: "cat", l2: "cat", level: "Intro"},
{l1: "caraid", l2: "friend", level: "Intro"},
{l1: "Calum", l2: "Calum", level: "Intro"},
{l1: "caileag", l2: "girl", level: "Intro"},
{l1: "bò", l2: "cow", level: "Intro"},
{l1: "beag", l2: "little", level: "Intro"},
{l1: "balach", l2: "boy", level: "Intro"},
{l1: "Anna", l2: "Anne", level: "Intro"},
{l1: "agus", l2: "and", level: "Intro"},
{l1: "uisge-beatha", l2: "Whisky", level: "Food and Drink"},
{l1: "uisge", l2: "Water", level: "Food and Drink"},
{l1: "taigeis", l2: "haggis", level: "Food and Drink"},
{l1: "sin", l2: "that", level: "Food and Drink"},
{l1: "sgadan", l2: "herring", level: "Food and Drink"},
{l1: "seo", l2: "this", level: "Food and Drink"},
{l1: "salann", l2: "salt", level: "Food and Drink"},
{l1: "rìs", l2: "rice", level: "Food and Drink"},
{l1: "piobar", l2: "pepper", level: "Food and Drink"},
{l1: "is toil leam", l2: "I like", level: "Food and Drink"},
{l1: "ìm", l2: "butter", level: "Food and Drink"},
{l1: "idir", l2: "at all", level: "Food and Drink"},
{l1: "iasg", l2: "fish", level: "Food and Drink"},
{l1: "hama", l2: "hama", level: "Food and Drink"},
{l1: "guga", l2: "guga", level: "Food and Drink"},
{l1: "cha toil leam", l2: "I do not like", level: "Food and Drink"},
{l1: "cèic", l2: "cake", level: "Food and Drink"},
{l1: "càise", l2: "cheese", level: "Food and Drink"},
{l1: "buntàta", l2: "potato", level: "Food and Drink"},
{l1: "brot", l2: "soup", level: "Food and Drink"},
{l1: "brochan", l2: "porridge", level: "Food and Drink"},
{l1: "blasta", l2: "tasty", level: "Food and Drink"},
{l1: "biadh", l2: "food", level: "Food and Drink"},
{l1: "aran", l2: "bread", level: "Food and Drink"},
{l1: "tìoraidh", l2: "cheerio", level: "Phrases"},
{l1: "tì", l2: "tea", level: "Phrases"},
{l1: "tapadh leibh", l2: "thank you (formal)", level: "Phrases"},
{l1: "tapadh leat", l2: "thank you (informal)", level: "Phrases"},
{l1: "slàinte", l2: "cheers/health", level: "Phrases"},
{l1: "siùcar", l2: "sugar", level: "Phrases"},
{l1: "sgoinneil", l2: "great", level: "Phrases"},
{l1: "ollaimh", l2: "professor", level: "Phrases"},
{l1: "oidhche mhath", l2: "good night", level: "Phrases"},
{l1: "oidhche", l2: "night", level: "Phrases"},
{l1: "madainn mhath", l2: "good morning", level: "Phrases"},
{l1: "leat", l2: "with you (le)", level: "Phrases"},
{l1: "Iseabail", l2: "Isabella", level: "Phrases"},
{l1: "halò", l2: "hello", level: "Phrases"},
{l1: "feasgar math", l2: "good afternoon", level: "Phrases"},
{l1: "fàilte", l2: "welcome", level: "Phrases"},
{l1: "Eilidh", l2: "Helen", level: "Phrases"},
{l1: "Ealasaid", l2: "Elizabeth", level: "Phrases"},
{l1: "cofaidh", l2: "coffee", level: "Phrases"},
{l1: "ceud mìle fàilte", l2: "one hundred thousand welcomes", level: "Phrases"},
{l1: "bainne", l2: "milk", level: "Phrases"},
{l1: "athair", l2: "father", level: "Phrases"},
{l1: "Anndra", l2: "Andrew", level: "Phrases"},
{l1: "Anna", l2: "Anne", level: "Phrases"},
{l1: "a thidseir", l2: "teacher (vocative)", level: "Phrases"},
{l1: "a sheanair", l2: "grandfather (vocative)", level: "Phrases"},
{l1: "a phiuthar", l2: "sister (vocative)", level: "Phrases"},
{l1: "a mhàthair", l2: "mother (vocative)", level: "Phrases"},
{l1: "a charaid", l2: "friend (vocative)", level: "Phrases"},
{l1: "a bhràthair", l2: "brother (vocative)", level: "Phrases"},
{l1: "a bhalaich", l2: "boy (vocative)", level: "Phrases"},
{l1: "toilichte", l2: "happy", level: "Feelings"},
{l1: "thu", l2: "you (informal)", level: "Feelings"},
{l1: "spòrsail", l2: "fun", level: "Feelings"},
{l1: "sibh", l2: "you (formal)", level: "Feelings"},
{l1: "sgìth", l2: "tired", level: "Feelings"},
{l1: "Seumas", l2: "James", level: "Feelings"},
{l1: "mi", l2: "me", level: "Feelings"},
{l1: "iseabail", l2: "Isabella", level: "Feelings"},
{l1: "i", l2: "she", level: "Feelings"},
{l1: "gu math", l2: "well", level: "Feelings"},
{l1: "gabh mo leisgeul", l2: "excuse me", level: "Feelings"},
{l1: "e", l2: "he", level: "Feelings"},
{l1: "duilich", l2: "sorry", level: "Feelings"},
{l1: "crosta", l2: "cross", level: "Feelings"},
{l1: "ciamar a tha", l2: "how is...", level: "Feelings"},
{l1: "cho", l2: "so", level: "Feelings"},
{l1: "ceart gu leòr", l2: "all right", level: "Feelings"},
{l1: "brònach", l2: "sad", level: "Feelings"},
{l1: "Anndra", l2: "Andrew", level: "Feelings"},
{l1: "a-nis", l2: "now", level: "Feelings"},
{l1: "air bhioran", l2: "excited", level: "Feelings"},
{l1: "trang", l2: "busy", level: "About Me"},
{l1: "steòrnabhagh", l2: "Stornoway", level: "About Me"},
{l1: "Seòras", l2: "George", level: "About Me"},
{l1: "sasainn", l2: "England", level: "About Me"},
{l1: "muile", l2: "Mull", level: "About Me"},
{l1: "mòr", l2: "big", level: "About Me"},
{l1: "Màiri", l2: "Mary", level: "About Me"},
{l1: "lunnainn", l2: "London", level: "About Me"},
{l1: "leòdhas", l2: "Lewis", level: "About Me"},
{l1: "inbhir nis", l2: "Inverness", level: "About Me"},
{l1: "ìle", l2: "Islay", level: "About Me"},
{l1: "Iain", l2: "John", level: "About Me"},
{l1: "glaschu", l2: "Glasgow", level: "About Me"},
{l1: "èirinn", l2: "Ireland", level: "About Me"},
{l1: "dùn èideann", l2: "Edinburgh", level: "About Me"},
{l1: "dùn", l2: "Dun", level: "About Me"},
{l1: "cò", l2: "Who", level: "About Me"},
{l1: "canada", l2: "Canada", level: "About Me"},
{l1: "barraigh", l2: "Barra", level: "About Me"},
{l1: "alba nuadh", l2: "Nova Scotia", level: "About Me"},
{l1: "alba", l2: "Scotland", level: "About Me"},
{l1: "àlainn", l2: "beautiful", level: "About Me"},
{l1: "aimearaga", l2: "America", level: "About Me"},
{l1: "orm", l2: "on me", level: "Clothing"},
{l1: "lèine", l2: "shirt", level: "Clothing"},
{l1: "lèine-t", l2: "t-shirt", level: "Clothing"},
{l1: "sgiort", l2: "skirt", level: "Clothing"},
{l1: "bròg", l2: "shoe", level: "Clothing"},
{l1: "seall", l2: "look", level: "Clothing"},
{l1: "briogais", l2: "trousers", level: "Clothing"},
{l1: "bòtannan", l2: "boots", level: "Clothing"},
{l1: "còta", l2: "coat", level: "Clothing"},
{l1: "ort", l2: "on you", level: "Clothing"},
{l1: "bonaid", l2: "bonnet", level: "Clothing"},
{l1: "drathais", l2: "pants", level: "Clothing"},
{l1: "ag iarraidh", l2: "wanting", level: "Clothing"},
{l1: "a' ceannach", l2: "buying", level: "Clothing"},
{l1: "dreasa", l2: "dress", level: "Clothing"},
{l1: "speuclairean", l2: "glasses", level: "Clothing"},
{l1: "geansaidh", l2: "jumper", level: "Clothing"},
{l1: "uaireadair", l2: "watch", level: "Clothing"},
{l1: "sinn", l2: "we", level: "Clothing"},
{l1: "iad", l2: "they", level: "Clothing"},
{l1: "stocainnean", l2: "socks", level: "Clothing"},
{l1: "fèileadh", l2: "kilt", level: "Clothing"},
{l1: "aodach", l2: "clothing", level: "Clothing"},
{l1: "seacaid", l2: "jacket", level: "Clothing"},
{l1: "agam", l2: "at me", level: "Pets"},
{l1: "luch", l2: "mouse", level: "Pets"},
{l1: "eun", l2: "a bird", level: "Pets"},
{l1: "cuilean", l2: "puppy", level: "Pets"},
{l1: "brèagha", l2: "pretty", level: "Pets"},
{l1: "peata", l2: "pet", level: "Pets"},
{l1: "agad", l2: "at you", level: "Pets"},
{l1: "uan", l2: "lamb", level: "Pets"},
{l1: "each", l2: "horse", level: "Pets"},
{l1: "caora", l2: "sheep", level: "Pets"},
{l1: "glè mhath", l2: "very good", level: "Pets"},
{l1: "glè bheag", l2: "very small", level: "Pets"},
{l1: "glè", l2: "very", level: "Pets"},
{l1: "losgann", l2: "frog", level: "Pets"},
{l1: "àrd", l2: "high", level: "Pets"},
{l1: "òg", l2: "young", level: "Pets"},
{l1: "èibhinn", l2: "funny", level: "Pets"},
{l1: "gòrach", l2: "stupid", level: "Pets"},
{l1: "a' faicinn", l2: "seeing", level: "Pets"},
{l1: "a' cluinntinn", l2: "hearing", level: "Pets"},
{l1: "damhan-allaidh", l2: "spider", level: "Pets"},
{l1: "radan", l2: "rat", level: "Pets"},
{l1: "coineanach", l2: "rabbit", level: "Pets"},
{l1: "gobhar", l2: "goat", level: "Pets"},
{l1: "fliuch", l2: "wet", level: "Weather"},
{l1: "fuar", l2: "cold", level: "Weather"},
{l1: "gaothach", l2: "Windy", level: "Weather"},
{l1: "blàth", l2: "warm", level: "Weather"},
{l1: "grianach", l2: "sunny", level: "Weather"},
{l1: "ceòthach", l2: "misty", level: "Weather"},
{l1: "garbh", l2: "rough", level: "Weather"},
{l1: "bheil", l2: "Is", level: "Weather"},
{l1: "a-muigh", l2: "outward", level: "Weather"},
{l1: "a' faireachdainn", l2: "Feeling", level: "Weather"},
{l1: "sgòthach", l2: "Cloudy", level: "Weather"},
{l1: "gu math", l2: "well", level: "Weather"},
{l1: "dorcha", l2: "dark", level: "Weather"},
{l1: "cuidich mi", l2: "help me", level: "Phrases 2"},
{l1: "slàinte mhath", l2: "Good health", level: "Phrases 2"},
{l1: "dè tha dol", l2: "what's up", level: "Phrases 2"},
{l1: "a chàirdean", l2: "friends (vocative)", level: "Phrases 2"},
{l1: "tìoraidh an-dràsta", l2: "cheerio now", level: "Phrases 2"},
{l1: "dè", l2: "what", level: "Phrases 2"},
{l1: "a-rithist", l2: "again", level: "Phrases 2"},
{l1: "mòran taing", l2: "many thanks", level: "Phrases 2"},
{l1: "'s e do bheatha", l2: "you're welcome", level: "Phrases 2"},
{l1: "feumaidh mi falbh", l2: "I have to go", level: "Phrases 2"},
{l1: "na gabh dragh", l2: "never mind", level: "Phrases 2"},
{l1: "a' tuigsinn", l2: "Understanding", level: "Phrases 2"},
{l1: "bruidhinn nas slaodaiche", l2: "talk more slowly", level: "Phrases 2"},
{l1: "can sin a-rithist", l2: "say that again", level: "Phrases 2"},
{l1: "mar sin leat", l2: "goodbye", level: "Phrases 2"},
{l1: "beatha", l2: "Life", level: "Phrases 2"},
{l1: "dè an t-ainm a th' ort", l2: "what's your name", level: "Phrases 2"},
{l1: "cailean", l2: "Colin", level: "Phrases 2"},
{l1: "beathag", l2: "Beth", level: "Phrases 2"},
{l1: "raonaid", l2: "Rachel", level: "Phrases 2"},
{l1: "ainm", l2: "Name", level: "Phrases 2"},
{l1: "Dòmhnall", l2: "Donald", level: "Phrases 2"},
{l1: "cuideachd", l2: "Also", level: "Phrases 2"},
{l1: "obh obh", l2: "oh no", level: "Phrases 2"},
{l1: "runrig", l2: "Runrig", level: "Phrases 2"},
{l1: "an t-uisge", l2: "the rain", level: "Rain etc."},
{l1: "sneachd", l2: "Snow", level: "Rain etc."},
{l1: "reòthadh", l2: "ice", level: "Rain etc."},
{l1: "ach", l2: "But", level: "Rain etc."},
{l1: "dealanaich", l2: "lightning", level: "Rain etc."},
{l1: "tàirneanaich", l2: "thunder", level: "Rain etc."},
{l1: "fhathast", l2: "still", level: "Rain etc."},
{l1: "no", l2: "or", level: "Rain etc."},
{l1: "an-dràsta", l2: "right now", level: "Rain etc."},
{l1: "an-diugh", l2: "today", level: "Rain etc."},
{l1: "cò ris a tha an t-sìde coltach", l2: "What is the weather like", level: "Rain etc."},
{l1: "aon chù", l2: "one dog", level: "Numbers"},
{l1: "bàta", l2: "boat", level: "Numbers"},
{l1: "aon bhàta", l2: "one boat", level: "Numbers"},
{l1: "aon chàr", l2: "one car", level: "Numbers"},
{l1: "bus", l2: "bus", level: "Numbers"},
{l1: "aon bhus", l2: "one bus", level: "Numbers"},
{l1: "càr", l2: "car", level: "Numbers"},
{l1: "aon", l2: "one", level: "Numbers"},
{l1: "cia mheud", l2: "how many", level: "Numbers"},
{l1: "asal", l2: "donkey", level: "Numbers"},
{l1: "eala", l2: "Swan", level: "Numbers"},
{l1: "uinneag", l2: "Window", level: "Numbers"},
{l1: "dà", l2: "two", level: "Numbers"},
{l1: "òran", l2: "a song", level: "Numbers"},
{l1: "dà chàr", l2: "Two cars", level: "Numbers"},
{l1: "dà bhus", l2: "Two buses", level: "Numbers"},
{l1: "dà mhuc", l2: "Two pigs", level: "Numbers"},
{l1: "dà phiseag", l2: "two kittens", level: "Numbers"},
{l1: "dà chù", l2: "Two dogs", level: "Numbers"},
{l1: "dà chat", l2: "Two cats", level: "Numbers"},
{l1: "bràthair", l2: "brother", level: "Family"},
{l1: "aon bhràthair", l2: "one brother", level: "Family"},
{l1: "bràithrean", l2: "Brothers", level: "Family"},
{l1: "piuthar", l2: "sister", level: "Family"},
{l1: "aon phiuthar", l2: "one sister", level: "Family"},
{l1: "seanair", l2: "grandfather", level: "Family"},
{l1: "athair", l2: "father", level: "Family"},
{l1: "mac", l2: "son", level: "Family"},
{l1: "teaghlach", l2: "family", level: "Family"},
{l1: "leanabh", l2: "a child", level: "Family"},
{l1: "peathraichean", l2: "Sisters", level: "Family"},
{l1: "bean", l2: "Wife", level: "Family"},
{l1: "seanmhair", l2: "grandmother", level: "Family"},
{l1: "nighean", l2: "daughter", level: "Family"},
{l1: "màthair", l2: "mother", level: "Family"},
{l1: "ainmeil", l2: "famous", level: "Family"},
{l1: "antaidh", l2: "Aunt", level: "Family"},
{l1: "uncail", l2: "uncle", level: "Family"},
{l1: "an duine agam", l2: "my husband", level: "Family"},
{l1: "againn", l2: "at us", level: "Family"},
{l1: "clann", l2: "children", level: "Family"},
{l1: "luath", l2: "quick", level: "Family"},
{l1: "reamhar", l2: "fat", level: "Family"},
{l1: "onarach", l2: "honest", level: "Family"},
{l1: "sgriosail", l2: "horrible", level: "Family"},
{l1: "laghach", l2: "nice", level: "Family"},
{l1: "neònach", l2: "weird", level: "Family"},
{l1: "leabhar", l2: "a book", level: "Numbers 2"},
{l1: "rathad", l2: "Road", level: "Numbers 2"},
{l1: "sgian", l2: "a knife", level: "Numbers 2"},
{l1: "sgillinn", l2: "a penny", level: "Numbers 2"},
{l1: "stais", l2: "moustache", level: "Numbers 2"},
{l1: "latha", l2: "day", level: "Numbers 2"},
{l1: "smiogaid", l2: "chin", level: "Numbers 2"},
{l1: "not", l2: "pound", level: "Numbers 2"},
{l1: "trì", l2: "three", level: "Numbers 2"},
{l1: "ceithir", l2: "four", level: "Numbers 2"},
{l1: "còig", l2: "five", level: "Numbers 2"},
{l1: "sia", l2: "six", level: "Numbers 2"},
{l1: "bàtaichean", l2: "boats", level: "Numbers 2"},
{l1: "mucan", l2: "pigs", level: "Numbers 2"},
{l1: "piseagan", l2: "kittens", level: "Numbers 2"},
{l1: "seachd", l2: "seven", level: "Numbers 2"},
{l1: "ochd", l2: "eight", level: "Numbers 2"},
{l1: "naoi", l2: "nine", level: "Numbers 2"},
{l1: "deich", l2: "ten", level: "Numbers 2"},
{l1: "coin", l2: "dogs", level: "Numbers 2"},
{l1: "cait", l2: "cats", level: "Numbers 2"},
{l1: "a' faighinn", l2: "getting", level: "Numbers 2"},
{l1: "sùgh", l2: "juice", level: "Food 2"},
{l1: "leann", l2: "beer", level: "Food 2"},
{l1: "sùbh-làir", l2: "strawberry", level: "Food 2"},
{l1: "uachdar", l2: "cream", level: "Food 2"},
{l1: "suiteas", l2: "sweeties", level: "Food 2"},
{l1: "fìon", l2: "Wine", level: "Food 2"},
{l1: "mions", l2: "mini", level: "Food 2"},
{l1: "botal", l2: "bottle", level: "Food 2"},
{l1: "brot", l2: "soup", level: "Food 2"},
{l1: "paidh", l2: "pie", level: "Food 2"},
{l1: "ubhal", l2: "apple", level: "Food 2"},
{l1: "orainsear", l2: "orange", level: "Food 2"},
{l1: "isbean", l2: "sausage", level: "Food 2"},
{l1: "aran", l2: "bread", level: "Food 2"},
{l1: "ìm", l2: "butter", level: "Food 2"},
{l1: "bu toil leam", l2: "i would like", level: "Food 2"},
{l1: "ag ithe", l2: "eating", level: "Food 2"},
{l1: "snèap", l2: "turnip", level: "Food 2"},
{l1: "reòiteag", l2: "ice cream", level: "Food 2"},
{l1: "biadh", l2: "Food", level: "Food 2"},
{l1: "ugh", l2: "an egg", level: "Food 2"},
{l1: "ag òl", l2: "drinking", level: "Food 2"},
{l1: "cha bu toil leam", l2: "i wouldn't like", level: "Food 2"},
{l1: "glè bhlasta", l2: "very tasty", level: "Food 2"},
{l1: "tomàto", l2: "tomonto", level: "Food 2"},
{l1: "uinnean", l2: "onion", level: "Food 2"},
{l1: "curran", l2: "carrot", level: "Food 2"},
{l1: "òl", l2: "drink", level: "Food 2"},
{l1: "aig", l2: "at", level: "Colors"},
{l1: "geal", l2: "White", level: "Colors"},
{l1: "dubh", l2: "black", level: "Colors"},
{l1: "orains", l2: "Orange", level: "Colors"},
{l1: "purpaidh", l2: "purple", level: "Colors"},
{l1: "ùr", l2: "new", level: "Colors"},
{l1: "e", l2: "he", level: "Colors"},
{l1: "pinc", l2: "pink", level: "Colors"},
{l1: "dearg", l2: "Red", level: "Colors"},
{l1: "gorm", l2: "blue", level: "Colors"},
{l1: "feumaidh mi", l2: "I need", level: "Colors"},
{l1: "feumaidh tu", l2: "You need", level: "Colors"},
{l1: "buidhe", l2: "yellow", level: "Colors"},
{l1: "glas", l2: "Gray", level: "Colors"},
{l1: "uaine", l2: "green", level: "Colors"},
{l1: "donn", l2: "Brown", level: "Colors"},
{l1: "liath", l2: "gray", level: "Colors"},
{l1: "briogais ghoirid", l2: "Short trousers", level: "Colors"},
{l1: "putan", l2: "button", level: "Colors"},
{l1: "goirid", l2: "short", level: "Colors"},
{l1: "gu leòr", l2: "enough", level: "Colors"},
{l1: "fada", l2: "long", level: "Colors"},
{l1: "a' dèanamh", l2: "doing", level: "Colors"},
{l1: "crios", l2: "belt", level: "Colors"},
{l1: "a' goid", l2: "stealing", level: "Colors"},
{l1: "a' cumail", l2: "keeps", level: "Colors"},
{l1: "deise", l2: "suit", level: "Colors"},
{l1: "eile", l2: "else", level: "Colors"},
{l1: "taigh", l2: "house", level: "Home"},
{l1: "gàrradh", l2: "garden", level: "Home"},
{l1: "coimpiutair", l2: "computer", level: "Home"},
{l1: "an toil leat", l2: "do you like", level: "Home"},
{l1: "deasg", l2: "desk", level: "Home"},
{l1: "iuchair", l2: "Key", level: "Home"},
{l1: "flat", l2: "flat", level: "Home"},
{l1: "bòrd", l2: "table", level: "Home"},
{l1: "preas", l2: "cupboard", level: "Home"},
{l1: "mapa", l2: "Map", level: "Home"},
{l1: "dealbh", l2: "picture", level: "Home"},
{l1: "soitheach", l2: "plate", level: "Home"},
{l1: "amar", l2: "bath", level: "Home"},
{l1: "eadar-lìon", l2: "Internet", level: "Home"},
{l1: "òrd", l2: "hammer", level: "Home"},
{l1: "aca", l2: "at them", level: "Home"},
{l1: "seòmar-cadail", l2: "bedroom", level: "Home"},
{l1: "sin", l2: "that", level: "Home"},
{l1: "aige", l2: "at him", level: "Home"},
{l1: "taigh-beag", l2: "toilet", level: "Home"},
{l1: "frids", l2: "fridge", level: "Home"},
{l1: "balla", l2: "wall", level: "Home"},
{l1: "seo", l2: "this", level: "Home"},
{l1: "càit a bheil", l2: "where is", level: "Home"},
{l1: "an toil leibh", l2: "do you (formal) like", level: "Home"},
{l1: "leabaidh", l2: "bed", level: "Home"},
{l1: "teine", l2: "fire", level: "Home"},
{l1: "doras", l2: "door", level: "Home"},
{l1: "aice", l2: "at her", level: "Home"},
]