export const WORDS = [
    {l1: "bainne", l2: "milk",},
{l1: "grianach", l2: "sunny",},
{l1: "sasainn", l2: "England",},
{l1: "agad", l2: "at you",},
{l1: "athair", l2: "father",},
{l1: "ceòthach", l2: "misty",},
{l1: "sgìth", l2: "tired",},
{l1: "briogais", l2: "trousers",},
{l1: "dùn èideann", l2: "Edinburgh",},
{l1: "spòrsail", l2: "fun",},
{l1: "sgoinneil", l2: "great",},
{l1: "luch", l2: "mouse",},
{l1: "cò às a tha thu", l2: "where are you from",},
{l1: "is toil leam", l2: "I like",},
{l1: "bròg", l2: "shoe",},
{l1: "canada", l2: "Canada",},
{l1: "feasgar math", l2: "good afternoon",},
{l1: "glè mhath", l2: "very good",},
{l1: "uisge", l2: "Water",},
{l1: "biadh", l2: "Food",},
{l1: "aodach", l2: "Clothing",},
{l1: "a' ceannach", l2: "buying",},
{l1: "e", l2: "he/it",},
{l1: "muile", l2: "Mull",},
{l1: "toilichte", l2: "happy",},
{l1: "hama", l2: "hama",},
{l1: "math", l2: "good",},
{l1: "fàilte", l2: "Welcome",},
{l1: "seall", l2: "look",},
{l1: "a' faicinn", l2: "Seeing",},
{l1: "barraigh", l2: "Barra",},
{l1: "madainn mhath", l2: "good morning",},
{l1: "seacaid", l2: "jacket",},
{l1: "halò", l2: "Hello",},
{l1: "i", l2: "she/it",},
{l1: "beag", l2: "Little",},
{l1: "caora", l2: "sheep",},
{l1: "seo", l2: "this",},
{l1: "dona", l2: "bad",},
{l1: "lèine", l2: "shirt",},
{l1: "gòrach", l2: "stupid",},
{l1: "blasta", l2: "delicious",},
{l1: "Anndra", l2: "Andrew",},
{l1: "brònach", l2: "sad",},
{l1: "marsaili", l2: "Margery",},
{l1: "aimearaga", l2: "America",},
{l1: "èirinn", l2: "Ireland",},
{l1: "buntàta", l2: "potato",},
{l1: "cèic", l2: "cake",},
{l1: "a-nis", l2: "now",},
{l1: "sgòthach", l2: "Cloudy",},
{l1: "rìs", l2: "rice",},
{l1: "iasg", l2: "fish",},
{l1: "fuar", l2: "cold",},
{l1: "gaothach", l2: "Windy",},
{l1: "drathais", l2: "pants",},
{l1: "uan", l2: "lamb",},
{l1: "bò", l2: "cow",},
{l1: "steòrnabhagh", l2: "Stornoway",},
{l1: "cearc", l2: "chicken",},
{l1: "losgann", l2: "frog",},
{l1: "ceart gu leòr", l2: "all right",},
{l1: "fèileadh", l2: "kilt",},
{l1: "bòtannan", l2: "boots",},
{l1: "Ealasaid", l2: "Elizabeth",},
{l1: "teth", l2: "hot",},
{l1: "trang", l2: "busy",},
{l1: "còta", l2: "coat",},
{l1: "cha toil leam", l2: "I do not like",},
{l1: "càise", l2: "Cheese",},
{l1: "balach", l2: "Boy",},
{l1: "oidhche mhath", l2: "good night",},
{l1: "tì", l2: "tea",},
{l1: "mi", l2: "me",},
{l1: "gabh mo leisgeul", l2: "excuse me",},
{l1: "blàth", l2: "warm",},
{l1: "inbhir nis", l2: "Inverness",},
{l1: "geansaidh", l2: "jumper",},
{l1: "alba", l2: "Scotland",},
{l1: "cù", l2: "dog",},
{l1: "coineanach", l2: "Rabbit",},
{l1: "thu", l2: "you",},
{l1: "Irn bru", l2: "Irn Bru",},
{l1: "brèagha", l2: "pretty",},
{l1: "a' cluinntinn", l2: "Hearing",},
{l1: "oidhche", l2: "night",},
{l1: "idir", l2: "at all",},
{l1: "duilich", l2: "sorry",},
{l1: "brot", l2: "soup",},
{l1: "orm", l2: "on me",},
{l1: "Iain", l2: "John",},
{l1: "ìm", l2: "butter",},
{l1: "cho", l2: "so",},
{l1: "leòdhas", l2: "Lewis",},
{l1: "aran", l2: "bread",},
{l1: "muc", l2: "pig",},
{l1: "cofaidh", l2: "coffee",},
{l1: "stocainnean", l2: "socks",},
{l1: "èibhinn", l2: "funny",},
{l1: "agus", l2: "and",},
{l1: "cuilean", l2: "puppy",},
{l1: "radan", l2: "rat",},
{l1: "crosta", l2: "cross",},
{l1: "Seòras", l2: "George",},
{l1: "ceud mìle fàilte", l2: "one hundred thousand welcomes",},
{l1: "caraid", l2: "friend",},
{l1: "each", l2: "horse",},
{l1: "sinn", l2: "we",},
{l1: "a' faireachdainn", l2: "Feeling",},
{l1: "siùcar", l2: "sugar",},
{l1: "tapadh leat", l2: "Thank you",},
{l1: "caileag", l2: "girl",},
{l1: "gobhar", l2: "Goat",},
{l1: "Màiri", l2: "Mary",},
{l1: "glè", l2: "very",},
{l1: "ìle", l2: "Islay",},
{l1: "iad", l2: "they",},
{l1: "lèine-t", l2: "a t-shirt",},
{l1: "sgiort", l2: "skirt",},
{l1: "slàinte", l2: "health / cheers",},
{l1: "lunnainn", l2: "London",},
{l1: "dreasa", l2: "dress",},
{l1: "bonaid", l2: "bonnet",},
{l1: "Mòrag", l2: "Morag",},
{l1: "piseag", l2: "kitten",},
{l1: "snog", l2: "nice",},
{l1: "eun", l2: "a bird",},
{l1: "òg", l2: "Young",},
{l1: "fliuch", l2: "wet",},
{l1: "agam", l2: "at me",},
{l1: "iseabail", l2: "Isabella",},
{l1: "peata", l2: "pet",},
{l1: "mòr", l2: "big",},
{l1: "àrd", l2: "high",},
{l1: "Eilidh", l2: "Helen",},
{l1: "uaireadair", l2: "watch",},
{l1: "piobar", l2: "pepper",},
{l1: "Anna", l2: "Anne",},
{l1: "taigeis", l2: "haggis",},
{l1: "grànda", l2: "ugly",},
{l1: "tìoraidh", l2: "Bye",},
{l1: "speuclairean", l2: "glasses",},
{l1: "glè bheag", l2: "very small",},
{l1: "salann", l2: "salt",},
{l1: "ort", l2: "on you",},
{l1: "gu math", l2: "well",},
{l1: "Seumas", l2: "James",},
{l1: "alba nuadh", l2: "Nova Scotia",},
{l1: "glaschu", l2: "Glasgow",},
{l1: "is mise", l2: "I am",},
{l1: "dorcha", l2: "dark",},
{l1: "ag iarraidh", l2: "wanting",},
{l1: "leat", l2: "with you",},
{l1: "cò", l2: "Who",},
{l1: "sgadan", l2: "Herring",},
{l1: "garbh", l2: "rough",},
{l1: "damhan-allaidh", l2: "spider",},
{l1: "sibh", l2: "you (plural, polite)",},
{l1: "a-muigh", l2: "outward",},
{l1: "àlainn", l2: "beautiful",},
{l1: "air bhioran", l2: "excited",},
{l1: "ollaimh", l2: "professor",},
{l1: "gàidhlig", l2: "Gaelic",},
{l1: "sin", l2: "that",},
{l1: "uisge-beatha", l2: "Whisky",},
{l1: "Calum", l2: "Calum",},
{l1: "tunnag", l2: "duck",},
{l1: "brochan", l2: "porridge",},
]